apiVersion: v2
name: meeting-service
description: A Helm chart for meetingteam meeting service
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common