{{- define "common.rbac" -}}
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.name" . }}
  {{- with .Values.rbac.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  {{- toYaml .Values.rbac.role.resources | nindent 3 }}
  verbs:
  {{- toYaml .Values.rbac.role.verbs | nindent 3 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.name" . }}
  {{- with .Values.rbac.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
  {{- toYaml .Values.rbac.rolebinding.subjects | nindent 2}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "common.name" . }}
{{- end }}
{{- end }}
