{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    {{- if .Values.service.additionalPorts }}
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      {{ if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
    {{- end}}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end}}