AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instances for NT548 lab

Parameters:
  PublicSubnetId:
    Type: String
    Description: ID of the Public Subnet
  PrivateSubnetId:
    Type: String
    Description: ID of the Private Subnet
  PublicSecurityGroupId:
    Type: String
    Description: ID of the Public EC2 Security Group
  PrivateSecurityGroupId:
    Type: String
    Description: ID of the Private EC2 Security Group
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:
  PublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e449927258d45bc4
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref PublicSecurityGroupId
      Tags:
        - Key: Name
          Value: public-ec2

  PrivateEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e449927258d45bc4
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnetId
      SecurityGroupIds:
        - !Ref PrivateSecurityGroupId
      Tags:
        - Key: Name
          Value: private-ec2

Outputs:
  PublicEC2PublicIp:
    Description: Public IP of the Public EC2 instance
    Value: !GetAtt PublicEC2.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicEC2PublicIp"
  PrivateEC2PrivateIp:
    Description: Private IP of the Private EC2 instance
    Value: !GetAtt PrivateEC2.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-PrivateEC2PrivateIp"